/**
 * CoachDashboard.jsx
 * Coach panel for monitoring multiple athletes, comparing metrics,
 * generating PDF reports, and identifying top performers.
 */
import { useState } from 'react';
import { motion } from 'framer-motion';
import RadarChart from '../components/RadarChart';
import TrendGraph from '../components/TrendGraph';
import Scorecard from '../components/Scorecard';

// Mock athlete data
const MOCK_ATHLETES = [
    {
        id: 'SAI-A001', name: 'Aarav Sharma', sport: 'Athletics', age: 19, state: 'Haryana',
        scores: { speed: 88, strength: 82, endurance: 90, skill: 75, reaction: 85, overall: 85, percentile: 92, rank: 12000 },
        trend: [72, 75, 78, 80, 83, 85], tests: 24, xp: 4200, level: 22, badges: 6
    },
    {
        id: 'SAI-A002', name: 'Priya Patel', sport: 'Basketball', age: 17, state: 'Gujarat',
        scores: { speed: 78, strength: 70, endurance: 75, skill: 92, reaction: 88, overall: 81, percentile: 88, rank: 18000 },
        trend: [65, 68, 72, 75, 78, 81], tests: 18, xp: 3200, level: 17, badges: 5
    },
    {
        id: 'SAI-A003', name: 'Vikram Singh', sport: 'Football', age: 20, state: 'Punjab',
        scores: { speed: 92, strength: 88, endurance: 80, skill: 70, reaction: 75, overall: 82, percentile: 89, rank: 16500 },
        trend: [68, 70, 74, 77, 80, 82], tests: 30, xp: 5100, level: 26, badges: 7
    },
    {
        id: 'SAI-A004', name: 'Ananya Iyer', sport: 'Cricket', age: 18, state: 'Kerala',
        scores: { speed: 72, strength: 65, endurance: 68, skill: 95, reaction: 90, overall: 78, percentile: 82, rank: 27000 },
        trend: [60, 63, 68, 72, 75, 78], tests: 15, xp: 2800, level: 15, badges: 4
    },
    {
        id: 'SAI-A005', name: 'Rohit Kumar', sport: 'Athletics', age: 21, state: 'Bihar',
        scores: { speed: 85, strength: 90, endurance: 82, skill: 60, reaction: 70, overall: 79, percentile: 84, rank: 24000 },
        trend: [55, 60, 65, 70, 75, 79], tests: 20, xp: 3400, level: 18, badges: 5
    },
    {
        id: 'SAI-A006', name: 'Meera Das', sport: 'Basketball', age: 16, state: 'West Bengal',
        scores: { speed: 70, strength: 62, endurance: 72, skill: 85, reaction: 82, overall: 74, percentile: 76, rank: 36000 },
        trend: [50, 55, 60, 66, 70, 74], tests: 12, xp: 2200, level: 12, badges: 3
    },
];

const SPORT_FILTERS = ['All', 'Athletics', 'Football', 'Basketball', 'Cricket'];

export default function CoachDashboard() {
    const [sportFilter, setSportFilter] = useState('All');
    const [selectedAthlete, setSelectedAthlete] = useState(null);
    const [compareAthletes, setCompareAthletes] = useState([]);
    const [showScorecard, setShowScorecard] = useState(false);
    const [view, setView] = useState('grid'); // grid, compare

    const filtered = sportFilter === 'All'
        ? MOCK_ATHLETES
        : MOCK_ATHLETES.filter(a => a.sport === sportFilter);

    const topPerformers = [...MOCK_ATHLETES].sort((a, b) => b.scores.overall - a.scores.overall).slice(0, 3);

    function toggleCompare(athlete) {
        setCompareAthletes(prev => {
            const exists = prev.find(a => a.id === athlete.id);
            if (exists) return prev.filter(a => a.id !== athlete.id);
            if (prev.length >= 2) return [prev[1], athlete];
            return [...prev, athlete];
        });
    }

    function generatePDFReport(athlete) {
        const report = `
ATHLETEAI — PERFORMANCE REPORT
================================
Athlete: ${athlete.name}
ID: ${athlete.id}
Sport: ${athlete.sport} | Age: ${athlete.age} | State: ${athlete.state}
Date: ${new Date().toLocaleDateString()}

MODULE SCORES
Speed:     ${athlete.scores.speed}/100
Strength:  ${athlete.scores.strength}/100
Endurance: ${athlete.scores.endurance}/100
Skill:     ${athlete.scores.skill}/100
Reaction:  ${athlete.scores.reaction}/100

OVERALL: ${athlete.scores.overall}/100 (Top ${Math.round(100 - athlete.scores.percentile)}%)
National Rank: #${athlete.scores.rank.toLocaleString()} / 150,000

Stats: ${athlete.tests} tests | ${athlete.xp} XP | Level ${athlete.level} | ${athlete.badges} badges

— Generated by AthleteAI Coach Dashboard
    `.trim();

        const blob = new Blob([report], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `AthleteAI_Report_${athlete.name.replace(/\s/g, '_')}.txt`;
        a.click();
        URL.revokeObjectURL(url);
    }

    return (
        <div style={{ maxWidth: '1200px', margin: '0 auto', padding: '24px 20px' }}>
            <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '24px', flexWrap: 'wrap', gap: '12px' }}>
                    <div>
                        <h1 style={{ fontSize: '1.8rem', fontWeight: 800 }}>
                            👨‍🏫 <span className="gradient-text">Coach Dashboard</span>
                        </h1>
                        <p style={{ color: 'var(--text-secondary)', fontSize: '0.9rem' }}>
                            Monitor athletes, compare metrics, identify top performers.
                        </p>
                    </div>
                    <div style={{ display: 'flex', gap: '8px' }}>
                        <button className={view === 'grid' ? 'btn-primary' : 'btn-secondary'} onClick={() => setView('grid')}
                            style={{ padding: '8px 16px', fontSize: '0.8rem' }}>📊 Athletes</button>
                        <button className={view === 'compare' ? 'btn-primary' : 'btn-secondary'} onClick={() => setView('compare')}
                            style={{ padding: '8px 16px', fontSize: '0.8rem' }}>⚖️ Compare ({compareAthletes.length})</button>
                    </div>
                </div>

                {/* Top Performers Banner */}
                <div className="glass-card" style={{ padding: '16px 20px', marginBottom: '20px', display: 'flex', alignItems: 'center', gap: '20px', overflowX: 'auto' }}>
                    <span style={{ fontSize: '0.7rem', fontWeight: 700, color: 'var(--text-muted)', textTransform: 'uppercase', whiteSpace: 'nowrap' }}>🏆 Top</span>
                    {topPerformers.map((a, i) => (
                        <div key={a.id} style={{ display: 'flex', alignItems: 'center', gap: '8px', whiteSpace: 'nowrap' }}>
                            <span style={{ fontSize: '1.1rem' }}>{['🥇', '🥈', '🥉'][i]}</span>
                            <span style={{ fontWeight: 700, fontSize: '0.85rem' }}>{a.name}</span>
                            <span style={{ color: 'var(--neon-green)', fontWeight: 800, fontSize: '0.85rem' }}>{a.scores.overall}</span>
                        </div>
                    ))}
                </div>

                {/* Sport Filter */}
                <div style={{ display: 'flex', gap: '8px', marginBottom: '20px', flexWrap: 'wrap' }}>
                    {SPORT_FILTERS.map(s => (
                        <button key={s}
                            className={s === sportFilter ? 'btn-primary' : 'btn-secondary'}
                            onClick={() => setSportFilter(s)}
                            style={{ padding: '8px 16px', fontSize: '0.8rem' }}>
                            {s}
                        </button>
                    ))}
                </div>

                {view === 'grid' ? (
                    /* ATHLETE GRID VIEW */
                    <div style={{
                        display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(340px, 1fr))',
                        gap: '16px', marginBottom: '24px',
                    }}>
                        {filtered.map((athlete) => (
                            <motion.div key={athlete.id} initial={{ opacity: 0 }} animate={{ opacity: 1 }}
                                className="glass-card glass-card-hover" style={{ padding: '20px', cursor: 'pointer' }}
                                onClick={() => setSelectedAthlete(athlete)}>
                                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'start', marginBottom: '12px' }}>
                                    <div>
                                        <div style={{ fontWeight: 700, fontSize: '1rem' }}>{athlete.name}</div>
                                        <div style={{ color: 'var(--text-muted)', fontSize: '0.75rem' }}>{athlete.id} • {athlete.sport} • {athlete.state}</div>
                                    </div>
                                    <div style={{ textAlign: 'right' }}>
                                        <div className="gradient-text" style={{ fontSize: '1.5rem', fontWeight: 900 }}>{athlete.scores.overall}</div>
                                        <div style={{ fontSize: '0.65rem', color: 'var(--text-muted)' }}>Score</div>
                                    </div>
                                </div>

                                {/* Mini radar */}
                                <RadarChart data={[athlete.scores.speed, athlete.scores.strength, athlete.scores.endurance, athlete.scores.skill, athlete.scores.reaction]} size={150} />

                                <div style={{ display: 'flex', gap: '6px', marginTop: '12px', flexWrap: 'wrap' }}>
                                    <span className="badge badge-green">Lv.{athlete.level}</span>
                                    <span className="badge badge-blue">{athlete.tests} tests</span>
                                    <span className="badge badge-green">🏅 {athlete.badges}</span>
                                </div>

                                <div style={{ display: 'flex', gap: '8px', marginTop: '12px' }}>
                                    <button className="btn-secondary" onClick={(e) => { e.stopPropagation(); toggleCompare(athlete); }}
                                        style={{
                                            flex: 1, padding: '8px', fontSize: '0.75rem',
                                            borderColor: compareAthletes.find(a => a.id === athlete.id) ? 'var(--neon-green)' : undefined,
                                        }}>
                                        {compareAthletes.find(a => a.id === athlete.id) ? '✓ Selected' : '⚖️ Compare'}
                                    </button>
                                    <button className="btn-secondary" onClick={(e) => { e.stopPropagation(); generatePDFReport(athlete); }}
                                        style={{ padding: '8px 12px', fontSize: '0.75rem' }}>📄</button>
                                </div>
                            </motion.div>
                        ))}
                    </div>
                ) : (
                    /* COMPARE VIEW */
                    <div>
                        {compareAthletes.length < 2 ? (
                            <div className="glass-card" style={{ padding: '40px', textAlign: 'center', marginBottom: '24px' }}>
                                <div style={{ fontSize: '1.5rem', marginBottom: '8px' }}>⚖️</div>
                                <div style={{ fontWeight: 600, color: 'var(--text-secondary)' }}>
                                    Select 2 athletes from the Athletes tab to compare.
                                </div>
                                <div style={{ color: 'var(--text-muted)', fontSize: '0.85rem' }}>({compareAthletes.length}/2 selected)</div>
                            </div>
                        ) : (
                            <>
                                <div style={{ display: 'grid', gridTemplateColumns: '1fr auto 1fr', gap: '20px', marginBottom: '24px', alignItems: 'center' }}>
                                    <AthleteCompareCard athlete={compareAthletes[0]} color="var(--neon-green)" />
                                    <div style={{ fontSize: '1.5rem', fontWeight: 900, color: 'var(--text-muted)' }}>VS</div>
                                    <AthleteCompareCard athlete={compareAthletes[1]} color="var(--electric-blue)" />
                                </div>

                                {/* Overlaid radar */}
                                <div className="glass-card" style={{ padding: '24px', textAlign: 'center', marginBottom: '24px' }}>
                                    <h3 style={{ fontSize: '1rem', fontWeight: 700, marginBottom: '16px' }}>Radar Comparison</h3>
                                    <RadarChart
                                        data={[compareAthletes[0].scores.speed, compareAthletes[0].scores.strength, compareAthletes[0].scores.endurance, compareAthletes[0].scores.skill, compareAthletes[0].scores.reaction]}
                                        compareData={[compareAthletes[1].scores.speed, compareAthletes[1].scores.strength, compareAthletes[1].scores.endurance, compareAthletes[1].scores.skill, compareAthletes[1].scores.reaction]}
                                        size={300}
                                    />
                                    <div style={{ display: 'flex', justifyContent: 'center', gap: '24px', marginTop: '12px', fontSize: '0.8rem' }}>
                                        <span><span style={{ color: 'var(--neon-green)' }}>●</span> {compareAthletes[0].name}</span>
                                        <span><span style={{ color: 'var(--electric-blue)' }}>●</span> {compareAthletes[1].name}</span>
                                    </div>
                                </div>

                                {/* Metric comparison table */}
                                <div className="glass-card" style={{ padding: '20px', marginBottom: '24px' }}>
                                    <h3 style={{ fontSize: '1rem', fontWeight: 700, marginBottom: '16px' }}>Score Breakdown</h3>
                                    {['speed', 'strength', 'endurance', 'skill', 'reaction', 'overall'].map(metric => {
                                        const a = compareAthletes[0].scores[metric];
                                        const b = compareAthletes[1].scores[metric];
                                        return (
                                            <div key={metric} style={{ display: 'flex', alignItems: 'center', gap: '12px', padding: '8px 0', borderBottom: '1px solid rgba(255,255,255,0.05)' }}>
                                                <span style={{ width: '80px', fontSize: '0.8rem', color: 'var(--text-secondary)', textTransform: 'capitalize', fontWeight: 600 }}>{metric}</span>
                                                <span style={{ width: '50px', textAlign: 'right', fontWeight: 700, color: a > b ? 'var(--neon-green)' : 'var(--text-secondary)' }}>{a}</span>
                                                <div style={{ flex: 1, display: 'flex', gap: '4px', alignItems: 'center' }}>
                                                    <div style={{ flex: a, height: '8px', borderRadius: '4px', background: 'var(--neon-green)', transition: 'all 0.5s' }} />
                                                    <div style={{ flex: b, height: '8px', borderRadius: '4px', background: 'var(--electric-blue)', transition: 'all 0.5s' }} />
                                                </div>
                                                <span style={{ width: '50px', fontWeight: 700, color: b > a ? 'var(--electric-blue)' : 'var(--text-secondary)' }}>{b}</span>
                                            </div>
                                        );
                                    })}
                                </div>
                            </>
                        )}
                    </div>
                )}

                {/* Athlete Detail Modal */}
                {selectedAthlete && (
                    <div style={{
                        position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.7)', backdropFilter: 'blur(10px)',
                        display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 200, padding: '20px',
                    }} onClick={() => { setSelectedAthlete(null); setShowScorecard(false); }}>
                        <motion.div initial={{ scale: 0.9 }} animate={{ scale: 1 }}
                            style={{ maxWidth: '650px', width: '100%', maxHeight: '90vh', overflow: 'auto' }}
                            onClick={e => e.stopPropagation()}>
                            {showScorecard ? (
                                <Scorecard
                                    athlete={selectedAthlete}
                                    scores={selectedAthlete.scores}
                                    onClose={() => setShowScorecard(false)}
                                />
                            ) : (
                                <div className="glass-card" style={{ padding: '28px' }}>
                                    <h2 style={{ fontSize: '1.3rem', fontWeight: 800, marginBottom: '16px' }}>
                                        {selectedAthlete.name}
                                        <span style={{ fontSize: '0.8rem', color: 'var(--text-muted)', fontWeight: 400, marginLeft: '8px' }}>
                                            {selectedAthlete.sport} • {selectedAthlete.state}
                                        </span>
                                    </h2>
                                    <RadarChart data={[selectedAthlete.scores.speed, selectedAthlete.scores.strength, selectedAthlete.scores.endurance, selectedAthlete.scores.skill, selectedAthlete.scores.reaction]} size={240} />
                                    <TrendGraph data={selectedAthlete.trend} labels={selectedAthlete.trend.map((_, i) => `W${i + 1}`)} height={140} title="Weekly Progress" />
                                    <div style={{ display: 'flex', gap: '10px', marginTop: '16px' }}>
                                        <button className="btn-primary" onClick={() => setShowScorecard(true)} style={{ flex: 1, padding: '12px', fontSize: '0.85rem' }}>📊 Scorecard</button>
                                        <button className="btn-secondary" onClick={() => generatePDFReport(selectedAthlete)} style={{ flex: 1, padding: '12px', fontSize: '0.85rem' }}>📄 Download Report</button>
                                        <button className="btn-secondary" onClick={() => setSelectedAthlete(null)} style={{ padding: '12px 16px', fontSize: '0.85rem' }}>✕</button>
                                    </div>
                                </div>
                            )}
                        </motion.div>
                    </div>
                )}
            </motion.div>
        </div>
    );
}

function AthleteCompareCard({ athlete, color }) {
    return (
        <div className="glass-card" style={{ padding: '20px', textAlign: 'center' }}>
            <div style={{ fontWeight: 700, fontSize: '1.1rem', marginBottom: '4px' }}>{athlete.name}</div>
            <div style={{ color: 'var(--text-muted)', fontSize: '0.8rem', marginBottom: '8px' }}>{athlete.sport}</div>
            <div style={{ fontSize: '2.5rem', fontWeight: 900, color, lineHeight: 1 }}>{athlete.scores.overall}</div>
            <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', marginTop: '4px' }}>Overall Score</div>
        </div>
    );
}
